# Generated by Django 5.2.7 on 2025-10-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('is_sent', models.BooleanField(default=False)),
                ('added_to_calendar', models.BooleanField(default=False)),
            ],
        ),
    ]
